### ISSUE TITLE
Provide version of govukFooter with Welsh translations

### ISSUE THREAD

**Issue by matthewmascord** [hmrc/design-system#100]
The govukFooter component (https://design-system.service.gov.uk/components/footer/) contains hard-coded English text for the copyright and licence statement. This issue has been referenced in issues:

https://github.com/alphagov/govuk-frontend/issues/1290
https://github.com/alphagov/govuk-frontend/issues/1291
https://github.com/alphagov/govuk-frontend/issues/1682

These issues have not been moved since April 2019

In order for service teams to have a version of the footer supporting Welsh, and so teams do not end up copying and pasting the govukFooter, the hmrc design system should provide a clone of govukFooter, called hmrcFooter, which is identical and kept in step with the govukFooter component except for:
- accepting a language parameter (with value en or cy)
- render Welsh translations (if language == cy)

**Comment by timsb** [comment]
@matthewmascord Has this issue been resolved now that we've forked the footer in hmrc-frontend?

**Comment by matthewmascord** [comment]
Component hmrcFooter now available in hmrc-frontend
